[package]
name = "fuzzy_cluster_means"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
egui = "0.19.0"
eframe = "0.19.0"
rfd = "0.10.0"
